---
- name: "Upgrade every package"
  yum:
    name:         "*"
    state:        latest
    update_cache: yes

- name: "Docker - Install package"
  yum:
    name:         "docker"
    state:        present

- name: "Docker - Install python lib"
  pip:
    name:   docker-py
    state:  present

- name: "Docker - start and enable service"
  service:
    name:     "docker"
    state:    started
    enabled:  yes

# TODO : download image only on required hosts
- name: "Docker - Pull base images"
  docker_image:
    name:   "{{ item }}"
    state:  present
    tag:    latest
  with_items:
    - horgix/zookeeper
    - horgix/mesos-slave
    - mesoscloud/mesos-master
    - mesoscloud/marathon
    #- traefik
