---
- name: "Docker - Pull service images"
  docker_image:
    name:   "{{ item }}"
    state:  present
    tag:    latest
  with_items:
    - gitlab/gitlab-ce
    - horgix/gitlab-runner
    - traefik
      #- jetty
      #- maven

- name: "Configure Traefik"
  include: traefik.yml
  tags:
    - svctraefik

- name: "Configure MesosUI"
  include: mesos-ui.yml
  tags:
    - mesos-ui
    - mesosui

- name: "Configure GitLab"
  include: gitlab.yml
  tags:
    - gitlab

# TODO : make identifiers variable
- name: "Get GitLab private token"
  uri:
    url:          "{{ gitlab.endpoint }}/api/v3/session?login=root&password={{ gitlab.root_password }}"
    method:       POST
    status_code:  "201"
  register: api_session
  tags:
    - gitlab
    - gitlab-runner
    - gitlab-content
    - token

- name: "Set GitLab private token as fact"
  set_fact:
    gitlab_private_token: "{{ api_session['json']['private_token'] }}"
  tags:
    - gitlab
    - gitlab-runner
    - gitlab-content
    - token

- name: "Configure GitLab content"
  include: gitlab-content.yml
  tags:
    - gitlab
    - gitlab-content

- name: "Configure GitLab Runner"
  include: gitlab-runner.yml
  tags:
    - gitlab-runner
