---
- name: "MesosUI - Run Marathon app"
  uri:
    url:          "{{ marathon.endpoint }}/v2/apps/mesosui"
    method:       PUT
    body:         '{{ lookup("template", "mesosui_marathon_app.json.j2") }}'
    body_format:  json
    status_code:  "100,200,201,204"
    user:         "{{ marathon.username }}"
    password:     "{{ marathon.password }}"
    HEADER_Content-Type:  "application/json"
